//! Fetch the current masternode list from a Dash Core node via RPC and write it
//! to a seed file consumed by `dash-spv`.
//!
//! The file format is:
//!
//! ```text
//! # Auto-generated by masternode-seeds-fetcher on <timestamp> for <network>
//! # Block height: <height>
//! # Source: dashd `masternode list json`
//! # <count> enabled masternodes
//! <ip>:<port>
//! ...
//! ```
//!
//! Non-comment lines are parsed as `SocketAddr`. Lines starting with `#` and
//! blank lines are ignored by the consumer.
//!
//! Typical usage from CI:
//!
//! ```bash
//! masternode-seeds-fetcher \
//!     --network mainnet \
//!     --rpc-url http://dashd.example:9998 \
//!     --rpc-user user --rpc-pass pass \
//!     --out dash-spv/seeds/mainnet.txt
//! ```

use std::collections::BTreeSet;
use std::fs;
use std::io::Write;
use std::net::SocketAddr;
use std::path::PathBuf;

use anyhow::{anyhow, Context, Result};
use clap::{Parser, ValueEnum};
use dashcore_rpc::{Auth, Client, RpcApi};

#[derive(Copy, Clone, Debug, ValueEnum)]
enum Network {
    Mainnet,
    Testnet,
}

impl Network {
    fn as_str(&self) -> &'static str {
        match self {
            Network::Mainnet => "mainnet",
            Network::Testnet => "testnet",
        }
    }

    fn default_p2p_port(&self) -> u16 {
        match self {
            Network::Mainnet => 9999,
            Network::Testnet => 19999,
        }
    }
}

#[derive(Parser, Debug)]
#[command(author, version, about = "Fetch masternode IPs via RPC and write a dash-spv seed file")]
struct Args {
    /// Target network. Determines the default P2P port written into the file
    /// when an address returned by RPC does not include one.
    #[arg(long, value_enum)]
    network: Network,

    /// JSON-RPC URL for the Dash Core node (e.g. http://127.0.0.1:9998).
    #[arg(long, env = "DASHD_RPC_URL")]
    rpc_url: String,

    /// RPC username.
    #[arg(long, env = "DASHD_RPC_USER")]
    rpc_user: String,

    /// RPC password.
    #[arg(long, env = "DASHD_RPC_PASS")]
    rpc_pass: String,

    /// Output file path. If omitted, `dash-spv/seeds/<network>.txt` relative to
    /// the current directory is used.
    #[arg(long)]
    out: Option<PathBuf>,

    /// Include masternodes in any state, not just `ENABLED`. The default is to
    /// filter to enabled masternodes so that the resulting peer list reflects
    /// nodes that are actually reachable.
    #[arg(long, default_value_t = false)]
    include_non_enabled: bool,
}

fn main() -> Result<()> {
    let args = Args::parse();

    let out_path = args
        .out
        .clone()
        .unwrap_or_else(|| PathBuf::from(format!("dash-spv/seeds/{}.txt", args.network.as_str())));

    let rpc =
        Client::new(&args.rpc_url, Auth::UserPass(args.rpc_user.clone(), args.rpc_pass.clone()))
            .with_context(|| format!("creating RPC client for {}", args.rpc_url))?;

    let block_count = rpc.get_block_count().context("get_block_count")?;

    let list = rpc.get_masternode_list(Some("json"), None).context("get_masternode_list")?;

    let total = list.len();

    let mut addrs: BTreeSet<SocketAddr> = BTreeSet::new();
    for (_key, mn) in list {
        if !args.include_non_enabled && !mn.status.eq_ignore_ascii_case("ENABLED") {
            continue;
        }
        let mut addr = mn.address;
        if addr.port() == 0 {
            addr.set_port(args.network.default_p2p_port());
        }
        addrs.insert(addr);
    }

    if addrs.is_empty() {
        return Err(anyhow!(
            "no masternode addresses returned by RPC (total entries: {}); refusing to overwrite {}",
            total,
            out_path.display()
        ));
    }

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating parent dir for {}", out_path.display()))?;
    }

    let timestamp = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ");

    let mut file = fs::File::create(&out_path)
        .with_context(|| format!("opening {} for write", out_path.display()))?;
    writeln!(
        file,
        "# Auto-generated by masternode-seeds-fetcher on {} for {}",
        timestamp,
        args.network.as_str()
    )?;
    writeln!(file, "# Block height: {}", block_count)?;
    writeln!(file, "# Source: dashd `masternode list json`")?;
    writeln!(
        file,
        "# {} addresses ({} total masternodes{})",
        addrs.len(),
        total,
        if args.include_non_enabled {
            ""
        } else {
            ", ENABLED only"
        }
    )?;
    writeln!(file, "# Do not edit manually — refreshed weekly by .github/workflows/update-masternode-seeds.yml")?;
    for addr in &addrs {
        writeln!(file, "{}", addr)?;
    }

    eprintln!(
        "wrote {} addresses for {} to {}",
        addrs.len(),
        args.network.as_str(),
        out_path.display()
    );

    Ok(())
}
