[workspace]
members = ["dash", "crypto", "dash-network", "hashes", "internals", "fuzz", "rpc-client", "rpc-json", "rpc-integration-test", "key-wallet", "key-wallet-manager", "key-wallet-ffi", "dash-spv", "dash-spv-ffi", "git-state", "dash-network-seeds", "masternode-seeds-fetcher", "dash-spv-bench"]
resolver = "2"

[workspace.dependencies]
# Packages shared across crates
bincode = { package = "grovedb-bincode", version = "=2.1.0" }
bincode_derive = { package = "grovedb-bincode-derive", version = "=2.1.0" }
futures = "0.3"
hex = "0.4"
hex_lit = "0.1.1"
rayon = "1.11"
secp256k1 = "0.33.1" # must match with version used in `bitcoin-crypto` and `dash-pkc`
serde = { version = "1.0.219", default-features = false }
zeroize = { version = "1.8", features = ["derive"] }

# Packages from `dashpay/base-sdk`, MUST share same version ACROSS crates
dash-pkc = { git = "https://github.com/dashpay/base-sdk", rev = "e6402ced257c370a586ade9840ebbf545a4b7926", default-features = false }
dash-types = { git = "https://github.com/dashpay/base-sdk", rev = "e6402ced257c370a586ade9840ebbf545a4b7926", default-features = false }

# Packages from `rust-bitcoin/rust-bitcoin`, `bitcoin-crypto` uses revision due to `secp256k1`
base58ck = { version = "0.5.0" }
bitcoin_hashes = { version = "0.14.101", default-features = false }
bitcoin-crypto = { git = "https://github.com/rust-bitcoin/rust-bitcoin", rev = "7ba35c7c1dd63892bfb9c9395bbd80e2ab5df516", default-features = false }
hex-conservative = { version = "1.3.0" }

[workspace.package]
authors = ["The rust-dashcore Developers"]
edition = "2024"
license = "CC0-1.0"
repository = "https://github.com/dashpay/rust-dashcore"
rust-version = "1.89.0"
version = "0.45.0"

[patch.crates-io]
dashcore_hashes = { path = "hashes" }
# Use directly from GitHub while we don't have ownership of the crate on crates.io
rs-x11-hash = { git = "https://github.com/dashpay/rs-x11-hash", tag = "0.1.9" }

[profile.release]
# Default to unwinding for most crates
panic = "unwind"

[profile.release.package.dash-fuzz]
# Disable LTO and keep debuginfo for honggfuzz to avoid link GC issues
codegen-units = 16
debug = 1

[profile.dev]
# Default to unwinding for most crates
