[package]
name = "dashcore_hashes"
description = "Hash functions used by the rust-dash eccosystem"
authors = ["Samuel Westrich <sam@dash.org>"]
edition = "2021"
categories = ["algorithms"]
keywords = [ "crypto", "dash", "hash", "digest" ]
readme = "README.md"
exclude = ["tests", "contrib"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
serde = ["dep:serde", "bitcoin_hashes/serde"]
serde-std = ["serde", "serde/std"]
x11 = ["rs-x11-hash"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bincode = { workspace = true, optional = true }
bitcoin_hashes = { workspace = true, features = ["std"] }
hex-conservative = { workspace = true }
rs-x11-hash = { version = "0.1.8", optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
serde_test = "1.0"
criterion = "0.5"
test-case = "3.3"

[target.wasm32-unknown-unknown.dev-dependencies]
wasm-bindgen-test = "0.3"

[[bench]]
name = "hashes"
harness = false

[[bench]]
name = "siphash"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(bench)', 'cfg(fuzzing)'] }
