use std::ffi::{CStr, CString};
use std::os::raw::c_char;

// Re-export all derived FFI types and destroy functions from dash-spv.
// These are generated by the `FFIType` derive macro in the dash-spv crate.
pub use dash_spv::sync::{
    dash_spv_ffi_block_headers_progress_destroy, dash_spv_ffi_blocks_progress_destroy,
    dash_spv_ffi_chain_lock_progress_destroy, dash_spv_ffi_filter_headers_progress_destroy,
    dash_spv_ffi_filters_progress_destroy, dash_spv_ffi_instant_send_progress_destroy,
    dash_spv_ffi_masternodes_progress_destroy, dash_spv_ffi_mempool_progress_destroy,
    dash_spv_ffi_sync_progress_destroy, dash_spv_ffi_sync_state_destroy, FFIBlockHeadersProgress,
    FFIBlocksProgress, FFIChainLockProgress, FFIFilterHeadersProgress, FFIFiltersProgress,
    FFIInstantSendProgress, FFIMasternodesProgress, FFIMempoolProgress, FFISyncProgress,
    FFISyncState,
};

pub use dash_spv::client::config::{dash_spv_ffi_mempool_strategy_destroy, FFIMempoolStrategy};
pub use dash_spv::types::{dash_spv_ffi_mempool_removal_reason_destroy, FFIMempoolRemovalReason};

/// Opaque handle to the wallet manager owned by the SPV client.
///
/// This is intentionally zero-sized so it can be used purely as an FFI handle
/// while still allowing Rust to cast to the underlying key-wallet manager
/// implementation when necessary.
#[repr(C)]
pub struct FFIWalletManager {
    _private: [u8; 0],
}

#[repr(C)]
pub struct FFIString {
    pub ptr: *mut c_char,
    pub length: usize,
}

impl FFIString {
    pub fn new(s: &str) -> Self {
        let c_string = CString::new(s).unwrap_or_else(|_| CString::new("").unwrap());
        // Compute length from the finalized CString to avoid mismatches when input contains NULs
        let length = c_string.as_bytes().len();
        FFIString {
            ptr: c_string.into_raw(),
            length,
        }
    }

    /// # Safety
    /// - `ptr` must be either null or point to a valid, NUL-terminated C string.
    /// - The pointer must remain valid for the duration of this call.
    pub unsafe fn from_ptr(ptr: *const c_char) -> Result<String, String> {
        if ptr.is_null() {
            return Err("Null pointer".to_string());
        }
        CStr::from_ptr(ptr).to_str().map(|s| s.to_string()).map_err(|e| e.to_string())
    }
}

/// # Safety
/// - `s.ptr` must be a pointer previously returned by `FFIString::new` or compatible.
/// - It must not be used after this call.
pub unsafe fn dash_spv_ffi_string_destroy(s: FFIString) {
    if !s.ptr.is_null() {
        let _ = CString::from_raw(s.ptr);
    }
}
