[package]
name = "dashcore-rpc"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>",
]
description = "RPC client library for the Dash Core JSON-RPC API."
keywords = ["crypto", "dash", "dash-core", "rpc"]
readme = "README.md"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "dashcore_rpc"
path = "src/lib.rs"

[dependencies]
dashcore-rpc-json = { path = "../rpc-json" }
hex-conservative = { workspace = true }

jsonrpc = "0.18.0"
tracing = "0.1"

# Used for deserialization of JSON.
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { version="1.0", features=["preserve_order"] }

[dev-dependencies]
test-case = "3.3"
