[package]
name = "dashcore-crypto"
version = { workspace = true }
authors = ["The Dash Core Developers"]
license = "CC0-1.0"
repository = "https://github.com/dashpay/rust-dashcore/"
description = "Cryptographic primitives shared by rust-dashcore crates."
categories = ["cryptography::cryptocurrencies"]
keywords = ["crypto", "dash", "bls"]
edition = "2021"

[features]
default = []

bincode = ["dep:bincode", "dep:bincode_derive", "dashcore_hashes/bincode"]
bls = ["dep:blsful", "dep:tracing"]
serde = ["dep:serde", "dash-types/serde", "dashcore_hashes/serde"]

[dependencies]
bincode = { workspace = true, optional = true }
bincode_derive = { workspace = true, optional = true }
blsful = { git = "https://github.com/dashpay/agora-blsful", rev = "0c34a7a488a0bd1c9a9a2196e793b303ad35c900", optional = true }
dash-types = { version = "=0.1.0-beta", default-features = false, features = ["codec"] }
dashcore_hashes = { path = "../hashes" }
hex = { version = "0.4" }
internals = { path = "../internals", package = "dashcore-private" }
serde = { version = "1.0.219", default-features = false, features = [ "derive", "alloc" ], optional = true }
thiserror = "2"
tracing = { version = "0.1", optional = true }

[lints.rust]
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(bench)', 'cfg(fuzzing)', 'cfg(kani)'] }

[dev-dependencies]
hex_lit = "0.1.1"
