// Auto-generated by fetch_terminal_blocks.py

use super::*;

pub fn load_testnet_terminal_blocks(manager: &mut TerminalBlockDataManager) {
    // Terminal block 387480
    {
        let data = include_str!("terminal_block_387480.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 400000
    {
        let data = include_str!("terminal_block_400000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 450000
    {
        let data = include_str!("terminal_block_450000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 500000
    {
        let data = include_str!("terminal_block_500000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 550000
    {
        let data = include_str!("terminal_block_550000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 600000
    {
        let data = include_str!("terminal_block_600000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 650000
    {
        let data = include_str!("terminal_block_650000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 700000
    {
        let data = include_str!("terminal_block_700000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 750000
    {
        let data = include_str!("terminal_block_750000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 760000
    {
        let data = include_str!("terminal_block_760000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 800000
    {
        let data = include_str!("terminal_block_800000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 850000
    {
        let data = include_str!("terminal_block_850000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

    // Terminal block 900000
    {
        let data = include_str!("terminal_block_900000.json");
        if let Ok(state) = serde_json::from_str::<TerminalBlockMasternodeState>(data) {
            manager.add_state(state);
        }
    }

}
