//! Synchronization management for the Dash SPV client.

mod block_headers;
mod blocks;
mod chainlock;
pub(super) mod download_coordinator;
mod events;
mod filter_headers;
mod filters;
mod identifier;
mod instantsend;
mod masternodes;
mod mempool;
mod progress;
mod sync_coordinator;
mod sync_manager;

pub use block_headers::{BlockHeadersManager, BlockHeadersProgress};
pub use blocks::{BlocksManager, BlocksProgress};
pub use chainlock::{ChainLockManager, ChainLockProgress};
pub use filter_headers::{FilterHeadersManager, FilterHeadersProgress};
pub use filters::{FiltersManager, FiltersProgress};
pub use instantsend::{InstantSendManager, InstantSendProgress};
pub use masternodes::{MasternodesManager, MasternodesProgress};
pub(crate) use mempool::MempoolManager;
pub use mempool::MempoolProgress;

pub use events::SyncEvent;
pub use identifier::ManagerIdentifier;
pub use progress::{ProgressPercentage, SyncProgress, SyncState};
pub use sync_coordinator::{Managers, SyncCoordinator};
pub use sync_manager::{SyncManager, SyncManagerProgress, SyncManagerTaskContext};

// FFI types and destroy functions generated by ffi-derive
#[cfg(feature = "ffi")]
pub use block_headers::{dash_spv_ffi_block_headers_progress_destroy, FFIBlockHeadersProgress};
#[cfg(feature = "ffi")]
pub use blocks::{dash_spv_ffi_blocks_progress_destroy, FFIBlocksProgress};
#[cfg(feature = "ffi")]
pub use chainlock::{dash_spv_ffi_chain_lock_progress_destroy, FFIChainLockProgress};
#[cfg(feature = "ffi")]
pub use filter_headers::{dash_spv_ffi_filter_headers_progress_destroy, FFIFilterHeadersProgress};
#[cfg(feature = "ffi")]
pub use filters::{dash_spv_ffi_filters_progress_destroy, FFIFiltersProgress};
#[cfg(feature = "ffi")]
pub use instantsend::{dash_spv_ffi_instant_send_progress_destroy, FFIInstantSendProgress};
#[cfg(feature = "ffi")]
pub use masternodes::{dash_spv_ffi_masternodes_progress_destroy, FFIMasternodesProgress};
#[cfg(feature = "ffi")]
pub use mempool::{dash_spv_ffi_mempool_progress_destroy, FFIMempoolProgress};
#[cfg(feature = "ffi")]
pub use progress::{
    dash_spv_ffi_sync_progress_destroy, dash_spv_ffi_sync_state_destroy, FFISyncProgress,
    FFISyncState,
};
